version: "3"

services:
  user_management:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd user_management && yarn start'
    ports:
      - "3000:3000"
    tty: true
